#!/bin/sh
if [ $UID != 0 ]; then
	echo This script must run as root
	exit 1
fi
PARTUUID=`lsblk -no PARTUUID $1`
if [ $? != 0 ]; then
	echo Please select a valid device/partition
	exit 1
fi
if [ "x$1" = "x" ]; then
	echo Argument required
	echo NOTE: partition must contain linux root
        echo example: sudo sh `basename $0` /dev/sda2
	exit 1
fi 
#
# CONFIGURATION
#
CONFIGLOC=/boot/loader/entries/arch.conf
TITLE="Arch Linux"
LINUX="/vmlinuz-linux"
INITRD="/initramfs-linux.img"
OPTIONS="root=PARTUUID=$PARTUUID rw"
#
# END OF CONFIGURATION
#
echo "PARTUUID: $PARTUUID"
echo "Writing config file to $CONFIGLOC"
echo -e "title\t$TITLE\nlinux\t$LINUX\ninitrd\t$INITRD\noptions\t$OPTIONS" > $CONFIGLOC
echo Done!
